=== stephenegbuna/WebServiceJava/src/User.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.stayahead.com/User"
        xmlns:tns="http://www.stayahead.com/User" elementFormDefault="qualified">

    <element name="user" type="tns:User"/>

    <complexType name="User">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="tns:String15Chars"/>
            <element name="dob" type="date"/>
            <element name="email" type="string"/>
            <element name="phone" type="string"/>
            <element name="isMale" type="boolean" nillable="true" maxOccurs="2" minOccurs="0" form="unqualified"/>
            <element name="address" type="tns:Address"/>

        </sequence>

    </complexType>

    <complexType name="Address">
        <sequence>
            <element name="street"/>
            <element name="town"/>
            <element name="postcode"/>
        </sequence>
    </complexType>

    <simpleType name="String15Chars">
        <restriction base="string">
            <maxLength value="15"/>
        </restriction>
    </simpleType>

    <simpleType name="id">
        <restriction>

            <pattern value="[0-9]*"/>
        </restriction>
    </simpleType>

</schema>

=== stephenegbuna/WebServiceJava/src/User.xml
<?xml version="1.0" encoding="utf-8" ?>
<tns:user xmlns:tns="http://www.stayahead.com/User"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.stayahead.com/User User.xsd">

    <tns:id>1000</tns:id>
    <tns:name>Emeka</tns:name>
    <tns:dob>2001-01-01</tns:dob>
    <tns:email>egbunachike@gmail.com</tns:email>
    <tns:phone>07960099530</tns:phone>
<!--    using unqualified to allow removal of tns // namespace-->
    <isMale>true</isMale>
    <tns:address>
        <tns:street>25 Eton Close</tns:street>
        <tns:town>London</tns:town>
        <tns:postcode>SW184UD</tns:postcode>
    </tns:address>
</tns:user>
